Parameters:
  ImageId:
    Type: String
  Environment:
    Type: String
    Default: Development
    AllowedValues:
      - Development
      - Production
      - Local
      - Integration
      - Test

Mappings:
  ContainerSpecsMap:
    Development:
      Memory: 0.5GB
      CPU: 512
    Production:
      Memory: 1GB
      CPU: 2048

Resources:
  TargetTrackerECSTaskLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/ecs/TaskTrackerECSTask"
  TaskTrackerECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Memory: !FindInMap [ ContainerSpecsMap,!Ref 'Environment',Memory ]
      Cpu: !FindInMap [ ContainerSpecsMap,!Ref 'Environment',CPU ]
      TaskRoleArn: !ImportValue TaskTrackerECSRoleArn
      NetworkMode: host #This should be awsvpc but facing issue while connecting to ALB. bridge mode is better option and will change it to bridge or awsvpc later.
      ContainerDefinitions:
        - Name: TargetTrackerAppContainer
          Image: !Ref ImageId
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref TargetTrackerECSTaskLogGroup
              awslogs-stream-prefix: ecs