Parameters:
  Environment:
    Type: String
    Default: Development
    AllowedValues:
      - Development
      - Production
      - Local
      - Integration
      - Test

Conditions:
  CreateDevSchedules: !Equals
    - !Ref Environment
    - Development

Mappings:
  InstanceTypeMap:
    Production:
      "InstanceType": "m4.large" #Put an appropriate instance type once ready for prod.
    Development:
      "InstanceType": "t3.micro"
  InstanceMinMax:
    Production:
      MinInstance: 2
      MaxInstance: 5
    Development:
      MinInstance: 1
      MaxInstance: 1
  #For now only Singapore and Sydney configurations are added. As an improvement use SSM commands to fetch these values
  ImageByRegionMap:
    ap-southeast-1:
      "HVM64": "ami-04e3e68fcfc9ca078"
    ap-southeast-2:
      "HVM64": "ami-012bb964803d474e5"
Resources:
  ALBSecuiryGroupHttpPortIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: 0.0.0.0/32
      IpProtocol: tcp
      Fromport: 80
      Toport: 80

  ALBSecuiryGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Group for ALB
      GroupName: CustomAppsALB-SG
      SecurityGroupEgress:
        - Egress
      SecurityGroupIngress:
        - !Ref ALBSecuiryGroupHttpPortIngress

  GenericALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      Name: GenericServicesALB #As the same ALB would be used for all underneath applications/microservices
      SecurityGroups:
        - !Ref ALBSecuiryGroup
      Subnets:
        - !ImportValue PublicSubnet1
        - !ImportValue PublicSubnet2


  TaskTrackerTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: TaskTrackerTG
      TargetType: instance
      VpcId: !ImportValue GenericVPC
      Protocol: HTTP
      Port: 8080 #This needs to be changed once n/w mode is changed
      Tags:
        - Key: Environment
          Value: !Ref 'Environment'

  #Create a Launch Template. Alternate option is Launch Configuration.
  TaskTrackerEC2ASGLT:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: TaskTrackerAppLT
      LaunchTemplateData:
        ImageId: !FindInMap [ImageByRegionMap,!Ref "AWS::Region",HVM64]
        InstanceType: !FindInMap [InstanceTypeMap,!Ref 'Environment',InstanceType]
        KeyName: keyur-new-mac-v1
        IamInstanceProfile:
          Arn: !ImportValue ECSInstanceProfileArn
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe
            yum update -y
            echo ECS_CLUSTER=TaskTrackerCluster >> /etc/ecs/ecs.config
            echo ECS_BACKEND_HOST= >> /etc/ecs/ecs.config

  #Create an Autoscaling Group and add it in TG
  TaskTrackerEC2ASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: TaskTrackerEC2ASG
      LaunchTemplate:
        LaunchTemplateId: !Ref TaskTrackerEC2ASGLT
        Version: !GetAtt TaskTrackerEC2ASGLT.LatestVersionNumber
      AvailabilityZones:
        - !ImportValue TaskTrackerAZ1
        - !ImportValue TaskTrackerAZ2
      MinSize: !FindInMap [InstanceMinMax, !Ref 'Environment',MinInstance]
      MaxSize: !FindInMap [InstanceMinMax, !Ref 'Environment',MaxInstance]
      VPCZoneIdentifier:
        - !ImportValue PrivateSubnet1
        - !ImportValue PrivateSubnet2
  TaskTrackerASGDown:
    Type: AWS::AutoScaling::ScheduledAction
    Condition: CreateDevSchedules
    Properties:
      AutoScalingGroupName: !Ref TaskTrackerEC2ASG
      MaxSize: 0
      MinSize: 0
      Recurrence: "0 12 * * *"
  TaskTrackerASGUp:
    Type: AWS::AutoScaling::ScheduledAction
    Condition: CreateDevSchedules
    Properties:
      AutoScalingGroupName: !Ref TaskTrackerEC2ASG
      MinSize: !FindInMap [ InstanceMinMax, !Ref 'Environment',MinInstance ]
      MaxSize: !FindInMap [ InstanceMinMax, !Ref 'Environment',MaxInstance ]
      Recurrence: "0 22 * * *"